import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

function Home( { posts } ) {
	// console.log(posts)
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<main className={styles.main}>
				{posts.map( ( post: any, i: number ) => <p key={i}>{post.title}</p> )}
			</main>

			<footer className={styles.footer} />
		</div>
	);
}


export async function getStaticProps() {
	const res = await fetch( "http://localhost:3100/api/posts" );
	const data = await res.json();
	const posts = data.docs;

	console.log( "posts", posts );

	if ( !posts ) {
		return {
			notFound: true,
		};
	}

	return {
		props: { posts },
	};
}

export default Home;
