import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

function Home( { posts } ) {
	// console.log(posts)
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<main>
				<h1>Guido Offermans</h1>
				{/* {posts?.map( ( post: any, i: number ) => <p key={i}>{post.title}</p> )} */}
			</main>

			<footer />
		</>
	);
}


// export const getStaticProps = async () => {
// 	const res   = await fetch( "http://localhost:3100/api/posts" );
// 	console.log( res );
// 	const data  = await res.json();
// 	console.log( "data", data );

// 	const posts = data?.docs;

// 	console.log( "posts", posts );

// 	if ( ! posts ) {
// 		return {
// 			notFound: true,
// 		};
// 	}

// 	return {
// 		props: { posts },
// 	};
// };

export default Home;
